### ISSUE TITLE
`private': nil is not a symbol 

### ISSUE THREAD

**Issue by heybenchen** [yonbergman/orly#6]
I'm receiving the following error in 0.0.13 after pulling some changes in git. 

Looks like it doesn't like the `private` declaration introduced in https://github.com/yonbergman/orly/pull/5/files#diff-6414bded609d8403dc5725865397c3ddR71.

```
/Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/lib/orly/tester.rb:71:in `private': nil is not a symbol (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/lib/orly/tester.rb:71:in `<class:Tester>'
	from /Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/lib/orly/tester.rb:6:in `<module:Orly>'
	from /Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/lib/orly/tester.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/lib/orly.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/orly-0.0.13/bin/orly:4:in `<top (required)>'
	from /usr/local/bin/orly:23:in `load'
	from /usr/local/bin/orly:23:in `<main>'
```

**Comment by yonbergman** [comment]
Thanks, released version 0.0.14 which addresses the issue
